{"cells": [{"metadata": {}, "cell_type": "markdown", "source": "#### imports"}, {"metadata": {}, "cell_type": "code", "source": "import itertools\nimport numpy as np\nimport matplotlib.pyplot as plt\nfrom matplotlib.ticker import NullFormatter\nimport pandas as pd\nimport numpy as np\nimport matplotlib.ticker as ticker\nfrom sklearn import preprocessing\n%matplotlib inline", "execution_count": 13, "outputs": []}, {"metadata": {}, "cell_type": "markdown", "source": "# load the data"}, {"metadata": {}, "cell_type": "code", "source": "!wget -O loan_train.csv https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/ML0101ENv3/labs/loan_train.csv", "execution_count": 14, "outputs": [{"output_type": "stream", "text": "--2021-10-10 19:04:43--  https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/ML0101ENv3/labs/loan_train.csv\nResolving s3-api.us-geo.objectstorage.softlayer.net (s3-api.us-geo.objectstorage.softlayer.net)... 67.228.254.196\nConnecting to s3-api.us-geo.objectstorage.softlayer.net (s3-api.us-geo.objectstorage.softlayer.net)|67.228.254.196|:443... connected.\nHTTP request sent, awaiting response... 200 OK\nLength: 23101 (23K) [text/csv]\nSaving to: \u2018loan_train.csv\u2019\n\nloan_train.csv      100%[===================>]  22.56K  --.-KB/s    in 0.1s    \n\n2021-10-10 19:04:44 (231 KB/s) - \u2018loan_train.csv\u2019 saved [23101/23101]\n\n", "name": "stdout"}]}, {"metadata": {}, "cell_type": "markdown", "source": "#### load csv into dataframe"}, {"metadata": {}, "cell_type": "code", "source": "df = pd.read_csv('loan_train.csv')\ndf.head()", "execution_count": 15, "outputs": [{"output_type": "execute_result", "execution_count": 15, "data": {"text/plain": "   Unnamed: 0  Unnamed: 0.1 loan_status  Principal  terms effective_date  \\\n0           0             0     PAIDOFF       1000     30       9/8/2016   \n1           2             2     PAIDOFF       1000     30       9/8/2016   \n2           3             3     PAIDOFF       1000     15       9/8/2016   \n3           4             4     PAIDOFF       1000     30       9/9/2016   \n4           6             6     PAIDOFF       1000     30       9/9/2016   \n\n    due_date  age             education  Gender  \n0  10/7/2016   45  High School or Below    male  \n1  10/7/2016   33              Bechalor  female  \n2  9/22/2016   27               college    male  \n3  10/8/2016   28               college  female  \n4  10/8/2016   29               college    male  ", "text/html": "<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Unnamed: 0</th>\n      <th>Unnamed: 0.1</th>\n      <th>loan_status</th>\n      <th>Principal</th>\n      <th>terms</th>\n      <th>effective_date</th>\n      <th>due_date</th>\n      <th>age</th>\n      <th>education</th>\n      <th>Gender</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>0</td>\n      <td>0</td>\n      <td>PAIDOFF</td>\n      <td>1000</td>\n      <td>30</td>\n      <td>9/8/2016</td>\n      <td>10/7/2016</td>\n      <td>45</td>\n      <td>High School or Below</td>\n      <td>male</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>2</td>\n      <td>2</td>\n      <td>PAIDOFF</td>\n      <td>1000</td>\n      <td>30</td>\n      <td>9/8/2016</td>\n      <td>10/7/2016</td>\n      <td>33</td>\n      <td>Bechalor</td>\n      <td>female</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>3</td>\n      <td>3</td>\n      <td>PAIDOFF</td>\n      <td>1000</td>\n      <td>15</td>\n      <td>9/8/2016</td>\n      <td>9/22/2016</td>\n      <td>27</td>\n      <td>college</td>\n      <td>male</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>4</td>\n      <td>4</td>\n      <td>PAIDOFF</td>\n      <td>1000</td>\n      <td>30</td>\n      <td>9/9/2016</td>\n      <td>10/8/2016</td>\n      <td>28</td>\n      <td>college</td>\n      <td>female</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>6</td>\n      <td>6</td>\n      <td>PAIDOFF</td>\n      <td>1000</td>\n      <td>30</td>\n      <td>9/9/2016</td>\n      <td>10/8/2016</td>\n      <td>29</td>\n      <td>college</td>\n      <td>male</td>\n    </tr>\n  </tbody>\n</table>\n</div>"}, "metadata": {}}]}, {"metadata": {}, "cell_type": "code", "source": "df.shape", "execution_count": 16, "outputs": [{"output_type": "execute_result", "execution_count": 16, "data": {"text/plain": "(346, 10)"}, "metadata": {}}]}, {"metadata": {}, "cell_type": "markdown", "source": "# clean the data"}, {"metadata": {}, "cell_type": "markdown", "source": "#### remove unamed"}, {"metadata": {}, "cell_type": "code", "source": "df = df.drop([\"Unnamed: 0\", \"Unnamed: 0.1\"], axis=1)\ndf.head()", "execution_count": 17, "outputs": [{"output_type": "execute_result", "execution_count": 17, "data": {"text/plain": "  loan_status  Principal  terms effective_date   due_date  age  \\\n0     PAIDOFF       1000     30       9/8/2016  10/7/2016   45   \n1     PAIDOFF       1000     30       9/8/2016  10/7/2016   33   \n2     PAIDOFF       1000     15       9/8/2016  9/22/2016   27   \n3     PAIDOFF       1000     30       9/9/2016  10/8/2016   28   \n4     PAIDOFF       1000     30       9/9/2016  10/8/2016   29   \n\n              education  Gender  \n0  High School or Below    male  \n1              Bechalor  female  \n2               college    male  \n3               college  female  \n4               college    male  ", "text/html": "<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>loan_status</th>\n      <th>Principal</th>\n      <th>terms</th>\n      <th>effective_date</th>\n      <th>due_date</th>\n      <th>age</th>\n      <th>education</th>\n      <th>Gender</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>PAIDOFF</td>\n      <td>1000</td>\n      <td>30</td>\n      <td>9/8/2016</td>\n      <td>10/7/2016</td>\n      <td>45</td>\n      <td>High School or Below</td>\n      <td>male</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>PAIDOFF</td>\n      <td>1000</td>\n      <td>30</td>\n      <td>9/8/2016</td>\n      <td>10/7/2016</td>\n      <td>33</td>\n      <td>Bechalor</td>\n      <td>female</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>PAIDOFF</td>\n      <td>1000</td>\n      <td>15</td>\n      <td>9/8/2016</td>\n      <td>9/22/2016</td>\n      <td>27</td>\n      <td>college</td>\n      <td>male</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>PAIDOFF</td>\n      <td>1000</td>\n      <td>30</td>\n      <td>9/9/2016</td>\n      <td>10/8/2016</td>\n      <td>28</td>\n      <td>college</td>\n      <td>female</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>PAIDOFF</td>\n      <td>1000</td>\n      <td>30</td>\n      <td>9/9/2016</td>\n      <td>10/8/2016</td>\n      <td>29</td>\n      <td>college</td>\n      <td>male</td>\n    </tr>\n  </tbody>\n</table>\n</div>"}, "metadata": {}}]}, {"metadata": {}, "cell_type": "markdown", "source": "#### convert date"}, {"metadata": {}, "cell_type": "code", "source": "df['due_date'] = pd.to_datetime(df['due_date'])\ndf['effective_date'] = pd.to_datetime(df['effective_date'])\ndf.head()", "execution_count": 18, "outputs": [{"output_type": "execute_result", "execution_count": 18, "data": {"text/plain": "  loan_status  Principal  terms effective_date   due_date  age  \\\n0     PAIDOFF       1000     30     2016-09-08 2016-10-07   45   \n1     PAIDOFF       1000     30     2016-09-08 2016-10-07   33   \n2     PAIDOFF       1000     15     2016-09-08 2016-09-22   27   \n3     PAIDOFF       1000     30     2016-09-09 2016-10-08   28   \n4     PAIDOFF       1000     30     2016-09-09 2016-10-08   29   \n\n              education  Gender  \n0  High School or Below    male  \n1              Bechalor  female  \n2               college    male  \n3               college  female  \n4               college    male  ", "text/html": "<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>loan_status</th>\n      <th>Principal</th>\n      <th>terms</th>\n      <th>effective_date</th>\n      <th>due_date</th>\n      <th>age</th>\n      <th>education</th>\n      <th>Gender</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>PAIDOFF</td>\n      <td>1000</td>\n      <td>30</td>\n      <td>2016-09-08</td>\n      <td>2016-10-07</td>\n      <td>45</td>\n      <td>High School or Below</td>\n      <td>male</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>PAIDOFF</td>\n      <td>1000</td>\n      <td>30</td>\n      <td>2016-09-08</td>\n      <td>2016-10-07</td>\n      <td>33</td>\n      <td>Bechalor</td>\n      <td>female</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>PAIDOFF</td>\n      <td>1000</td>\n      <td>15</td>\n      <td>2016-09-08</td>\n      <td>2016-09-22</td>\n      <td>27</td>\n      <td>college</td>\n      <td>male</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>PAIDOFF</td>\n      <td>1000</td>\n      <td>30</td>\n      <td>2016-09-09</td>\n      <td>2016-10-08</td>\n      <td>28</td>\n      <td>college</td>\n      <td>female</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>PAIDOFF</td>\n      <td>1000</td>\n      <td>30</td>\n      <td>2016-09-09</td>\n      <td>2016-10-08</td>\n      <td>29</td>\n      <td>college</td>\n      <td>male</td>\n    </tr>\n  </tbody>\n</table>\n</div>"}, "metadata": {}}]}, {"metadata": {}, "cell_type": "markdown", "source": "#### loan_status column is what we want to predict (target)"}, {"metadata": {}, "cell_type": "code", "source": "print(df['loan_status'].unique())\nprint(df['loan_status'].value_counts())", "execution_count": 19, "outputs": [{"output_type": "stream", "text": "['PAIDOFF' 'COLLECTION']\nPAIDOFF       260\nCOLLECTION     86\nName: loan_status, dtype: int64\n", "name": "stdout"}]}, {"metadata": {}, "cell_type": "markdown", "source": "#### convert male to 0 and female to 1"}, {"metadata": {}, "cell_type": "code", "source": "df['Gender'].replace(to_replace=['male','female'], value=[0,1],inplace=True)\ndf.head()", "execution_count": 20, "outputs": [{"output_type": "execute_result", "execution_count": 20, "data": {"text/plain": "  loan_status  Principal  terms effective_date   due_date  age  \\\n0     PAIDOFF       1000     30     2016-09-08 2016-10-07   45   \n1     PAIDOFF       1000     30     2016-09-08 2016-10-07   33   \n2     PAIDOFF       1000     15     2016-09-08 2016-09-22   27   \n3     PAIDOFF       1000     30     2016-09-09 2016-10-08   28   \n4     PAIDOFF       1000     30     2016-09-09 2016-10-08   29   \n\n              education  Gender  \n0  High School or Below       0  \n1              Bechalor       1  \n2               college       0  \n3               college       1  \n4               college       0  ", "text/html": "<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>loan_status</th>\n      <th>Principal</th>\n      <th>terms</th>\n      <th>effective_date</th>\n      <th>due_date</th>\n      <th>age</th>\n      <th>education</th>\n      <th>Gender</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>PAIDOFF</td>\n      <td>1000</td>\n      <td>30</td>\n      <td>2016-09-08</td>\n      <td>2016-10-07</td>\n      <td>45</td>\n      <td>High School or Below</td>\n      <td>0</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>PAIDOFF</td>\n      <td>1000</td>\n      <td>30</td>\n      <td>2016-09-08</td>\n      <td>2016-10-07</td>\n      <td>33</td>\n      <td>Bechalor</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>PAIDOFF</td>\n      <td>1000</td>\n      <td>15</td>\n      <td>2016-09-08</td>\n      <td>2016-09-22</td>\n      <td>27</td>\n      <td>college</td>\n      <td>0</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>PAIDOFF</td>\n      <td>1000</td>\n      <td>30</td>\n      <td>2016-09-09</td>\n      <td>2016-10-08</td>\n      <td>28</td>\n      <td>college</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>PAIDOFF</td>\n      <td>1000</td>\n      <td>30</td>\n      <td>2016-09-09</td>\n      <td>2016-10-08</td>\n      <td>29</td>\n      <td>college</td>\n      <td>0</td>\n    </tr>\n  </tbody>\n</table>\n</div>"}, "metadata": {}}]}, {"metadata": {}, "cell_type": "markdown", "source": "#### set a column for categorical variable with 0 or 1"}, {"metadata": {}, "cell_type": "code", "source": "print(df['education'].unique())\nprint(df['education'].value_counts())", "execution_count": 21, "outputs": [{"output_type": "stream", "text": "['High School or Below' 'Bechalor' 'college' 'Master or Above']\nHigh School or Below    151\ncollege                 149\nBechalor                 44\nMaster or Above           2\nName: education, dtype: int64\n", "name": "stdout"}]}, {"metadata": {}, "cell_type": "code", "source": "# keep non categorical columns\nFeature = df[['Principal','terms','age','Gender']]\n# set a column for each categorical value\nFeature = pd.concat([Feature,pd.get_dummies(df['education'])], axis=1)\n# drop \"Master or above\" column, too few values\nFeature.drop(['Master or Above'], axis = 1,inplace=True)\nFeature.head()", "execution_count": 25, "outputs": [{"output_type": "execute_result", "execution_count": 25, "data": {"text/plain": "   Principal  terms  age  Gender  Bechalor  High School or Below  college\n0       1000     30   45       0         0                     1        0\n1       1000     30   33       1         1                     0        0\n2       1000     15   27       0         0                     0        1\n3       1000     30   28       1         0                     0        1\n4       1000     30   29       0         0                     0        1", "text/html": "<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Principal</th>\n      <th>terms</th>\n      <th>age</th>\n      <th>Gender</th>\n      <th>Bechalor</th>\n      <th>High School or Below</th>\n      <th>college</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>1000</td>\n      <td>30</td>\n      <td>45</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1</td>\n      <td>0</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>1000</td>\n      <td>30</td>\n      <td>33</td>\n      <td>1</td>\n      <td>1</td>\n      <td>0</td>\n      <td>0</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>1000</td>\n      <td>15</td>\n      <td>27</td>\n      <td>0</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>1000</td>\n      <td>30</td>\n      <td>28</td>\n      <td>1</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>1000</td>\n      <td>30</td>\n      <td>29</td>\n      <td>0</td>\n      <td>0</td>\n      <td>0</td>\n      <td>1</td>\n    </tr>\n  </tbody>\n</table>\n</div>"}, "metadata": {}}]}, {"metadata": {}, "cell_type": "markdown", "source": "#### set X and Y for classification"}, {"metadata": {}, "cell_type": "code", "source": "X = Feature\ny = df['loan_status'].values", "execution_count": 30, "outputs": []}, {"metadata": {}, "cell_type": "markdown", "source": "#### Normalize Data"}, {"metadata": {}, "cell_type": "code", "source": "X = preprocessing.StandardScaler().fit(X).transform(X)", "execution_count": 31, "outputs": []}, {"metadata": {}, "cell_type": "markdown", "source": "# Classification"}, {"metadata": {}, "cell_type": "markdown", "source": "#### split the dataset"}, {"metadata": {}, "cell_type": "code", "source": "from sklearn.model_selection import train_test_split\n\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)\nprint ('Train set:', X_train.shape,  y_train.shape)\nprint ('Test set:', X_test.shape,  y_test.shape)", "execution_count": 47, "outputs": [{"output_type": "stream", "text": "Train set: (276, 7) (276,)\nTest set: (70, 7) (70,)\n", "name": "stdout"}]}, {"metadata": {}, "cell_type": "markdown", "source": "## KNN"}, {"metadata": {}, "cell_type": "code", "source": "from sklearn.neighbors import KNeighborsClassifier\n\n# train Model and Predict with k = 3\nkNN_model = KNeighborsClassifier(n_neighbors=3)\nkNN_model.fit(X_train, y_train)\nkNN_model.score(X_test, y_test)", "execution_count": 56, "outputs": [{"output_type": "execute_result", "execution_count": 56, "data": {"text/plain": "0.5714285714285714"}, "metadata": {}}]}, {"metadata": {}, "cell_type": "code", "source": "# use GridSearchCV to get best hyperparameters for KNN\nfrom sklearn.model_selection import GridSearchCV\n\nparam_grid = {'n_neighbors' : np.arange(1, 20), 'metric' : ['euclidiean', 'manhattan']}\n\ngrid = GridSearchCV(KNeighborsClassifier(), param_grid, cv=5)\ngrid.fit(X_train, y_train)", "execution_count": 57, "outputs": [{"output_type": "stream", "text": "/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 1157, in fit\n    return self._fit(X)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 350, in _fit\n    self._check_algorithm_metric()\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/neighbors/_base.py\", line 332, in _check_algorithm_metric\n    raise ValueError(\"Metric '%s' not valid. Use \"\nValueError: Metric 'euclidiean' not valid. Use sorted(sklearn.neighbors.VALID_METRICS['brute']) to get valid options. Metric can also be a callable function.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n", "name": "stderr"}, {"output_type": "execute_result", "execution_count": 57, "data": {"text/plain": "GridSearchCV(cv=5, estimator=KNeighborsClassifier(),\n             param_grid={'metric': ['euclidiean', 'manhattan'],\n                         'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,\n       18, 19])})"}, "metadata": {}}]}, {"metadata": {}, "cell_type": "code", "source": "print(\"best score for KNN\", grid.best_score_)\nprint(\"best hypermarameters for KNN\", grid.best_params_)", "execution_count": 58, "outputs": [{"output_type": "stream", "text": "best score 0.7283116883116884\nbest hypermarameters for knn {'metric': 'manhattan', 'n_neighbors': 19}\n", "name": "stdout"}]}, {"metadata": {}, "cell_type": "code", "source": "kNN_model = grid.best_estimator_\nkNN_model.score(X_test, y_test)", "execution_count": 59, "outputs": [{"output_type": "execute_result", "execution_count": 59, "data": {"text/plain": "0.6571428571428571"}, "metadata": {}}]}, {"metadata": {}, "cell_type": "markdown", "source": "## Decision tree"}, {"metadata": {}, "cell_type": "code", "source": "from sklearn.tree import DecisionTreeClassifier\n\nDT_model = DecisionTreeClassifier()\nDT_model.fit(X_train,y_train)\nDT_model.score(X_test, y_test)", "execution_count": 83, "outputs": [{"output_type": "execute_result", "execution_count": 83, "data": {"text/plain": "0.45714285714285713"}, "metadata": {}}]}, {"metadata": {}, "cell_type": "code", "source": "param_grid = {'criterion' : ['gini', 'entropy'], 'max_depth' : np.arange(1, 20)}\n\ngrid = GridSearchCV(DecisionTreeClassifier(), param_grid, cv=5)\ngrid.fit(X_train, y_train)", "execution_count": 84, "outputs": [{"output_type": "execute_result", "execution_count": 84, "data": {"text/plain": "GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),\n             param_grid={'criterion': ['gini', 'entropy'],\n                         'max_depth': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,\n       18, 19])})"}, "metadata": {}}]}, {"metadata": {}, "cell_type": "code", "source": "print(\"best score for Decision Tree\", grid.best_score_)\nprint(\"best hypermarameters for Decision Tree\", grid.best_params_)", "execution_count": 85, "outputs": [{"output_type": "stream", "text": "best score for KNN 0.7500000000000001\nbest hypermarameters for KNN {'criterion': 'gini', 'max_depth': 1}\n", "name": "stdout"}]}, {"metadata": {}, "cell_type": "code", "source": "DT_model = grid.best_estimator_\nDT_model.score(X_test, y_test)", "execution_count": 86, "outputs": [{"output_type": "execute_result", "execution_count": 86, "data": {"text/plain": "0.7571428571428571"}, "metadata": {}}]}, {"metadata": {}, "cell_type": "markdown", "source": "## Support Vector Machine"}, {"metadata": {}, "cell_type": "code", "source": "from sklearn import svm\n\nSVM_model = svm.SVC()\nSVM_model.fit(X_train, y_train)\nSVM_model.score(X_test, y_test)", "execution_count": 87, "outputs": [{"output_type": "execute_result", "execution_count": 87, "data": {"text/plain": "0.7571428571428571"}, "metadata": {}}]}, {"metadata": {}, "cell_type": "code", "source": "param_grid = {'C': [0.1, 1, 10, 100, 1000],\n              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],\n              'kernel': ['rbf']}\n\ngrid = GridSearchCV(svm.SVC(), param_grid, cv=5)\ngrid.fit(X_train, y_train)", "execution_count": 88, "outputs": [{"output_type": "execute_result", "execution_count": 88, "data": {"text/plain": "GridSearchCV(cv=5, estimator=SVC(),\n             param_grid={'C': [0.1, 1, 10, 100, 1000],\n                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],\n                         'kernel': ['rbf']})"}, "metadata": {}}]}, {"metadata": {}, "cell_type": "code", "source": "print(\"best score for SVM\", grid.best_score_)\nprint(\"best hypermarameters for SVM\", grid.best_params_)", "execution_count": 89, "outputs": [{"output_type": "stream", "text": "best score for KNN 0.7500000000000001\nbest hypermarameters for KNN {'C': 0.1, 'gamma': 1, 'kernel': 'rbf'}\n", "name": "stdout"}]}, {"metadata": {}, "cell_type": "code", "source": "SVM_model = grid.best_estimator_\nSVM_model.score(X_test, y_test)", "execution_count": 90, "outputs": [{"output_type": "execute_result", "execution_count": 90, "data": {"text/plain": "0.7571428571428571"}, "metadata": {}}]}, {"metadata": {}, "cell_type": "markdown", "source": "## Logistic Regression"}, {"metadata": {}, "cell_type": "code", "source": "from sklearn.linear_model import LogisticRegression\n\nLR_model = LogisticRegression()\nLR_model.fit(X_train,y_train)\nLR_model.score(X_test, y_test)", "execution_count": 92, "outputs": [{"output_type": "execute_result", "execution_count": 92, "data": {"text/plain": "0.7571428571428571"}, "metadata": {}}]}, {"metadata": {}, "cell_type": "code", "source": "param_grid = {\"C\":np.logspace(-3,3,7), \"penalty\":[\"l1\",\"l2\"]}\n\ngrid = GridSearchCV(LogisticRegression(), param_grid, cv=5)\ngrid.fit(X_train, y_train)", "execution_count": 93, "outputs": [{"output_type": "stream", "text": "/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 1304, in fit\n    solver = _check_solver(self.solver, self.penalty, self.dual)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 442, in _check_solver\n    raise ValueError(\"Solver %s supports only 'l2' or 'none' penalties, \"\nValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 1304, in fit\n    solver = _check_solver(self.solver, self.penalty, self.dual)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 442, in _check_solver\n    raise ValueError(\"Solver %s supports only 'l2' or 'none' penalties, \"\nValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 1304, in fit\n    solver = _check_solver(self.solver, self.penalty, self.dual)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 442, in _check_solver\n    raise ValueError(\"Solver %s supports only 'l2' or 'none' penalties, \"\nValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 1304, in fit\n    solver = _check_solver(self.solver, self.penalty, self.dual)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 442, in _check_solver\n    raise ValueError(\"Solver %s supports only 'l2' or 'none' penalties, \"\nValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 1304, in fit\n    solver = _check_solver(self.solver, self.penalty, self.dual)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 442, in _check_solver\n    raise ValueError(\"Solver %s supports only 'l2' or 'none' penalties, \"\nValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 1304, in fit\n    solver = _check_solver(self.solver, self.penalty, self.dual)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 442, in _check_solver\n    raise ValueError(\"Solver %s supports only 'l2' or 'none' penalties, \"\nValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \nTraceback (most recent call last):\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 531, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 1304, in fit\n    solver = _check_solver(self.solver, self.penalty, self.dual)\n  File \"/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py\", line 442, in _check_solver\n    raise ValueError(\"Solver %s supports only 'l2' or 'none' penalties, \"\nValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.\n\n  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n", "name": "stderr"}, {"output_type": "execute_result", "execution_count": 93, "data": {"text/plain": "GridSearchCV(cv=5, estimator=LogisticRegression(),\n             param_grid={'C': array([1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03]),\n                         'penalty': ['l1', 'l2']})"}, "metadata": {}}]}, {"metadata": {}, "cell_type": "code", "source": "print(\"best score for Linear Regression\", grid.best_score_)\nprint(\"best hypermarameters for Linear Regression\", grid.best_params_)", "execution_count": 94, "outputs": [{"output_type": "stream", "text": "best score for Linear Regression 0.7500000000000001\nbest hypermarameters for Linear Regression {'C': 0.001, 'penalty': 'l2'}\n", "name": "stdout"}]}, {"metadata": {}, "cell_type": "code", "source": "LR_model = grid.best_estimator_\nLR_model.score(X_test, y_test)", "execution_count": 95, "outputs": [{"output_type": "execute_result", "execution_count": 95, "data": {"text/plain": "0.7571428571428571"}, "metadata": {}}]}, {"metadata": {}, "cell_type": "markdown", "source": "# Model accuracy"}, {"metadata": {}, "cell_type": "code", "source": "from sklearn.metrics import jaccard_score\nfrom sklearn.metrics import f1_score\nfrom sklearn.metrics import log_loss", "execution_count": 139, "outputs": []}, {"metadata": {}, "cell_type": "code", "source": "y_pred = kNN_model.predict(X_test)\nprint(\"KNN Jaccard :\", jaccard_score(y_test, y_pred, average=None)[1])\nprint(\"KNN F1-score :\", f1_score(y_test, y_pred, average='weighted'))", "execution_count": 140, "outputs": [{"output_type": "stream", "text": "KNN Jaccard : 0.6571428571428571\nKNN F1-score : 0.6004926108374384\n", "name": "stdout"}]}, {"metadata": {}, "cell_type": "code", "source": "y_pred = DT_model.predict(X_test)\nprint(\"Decision Tree Jaccard :\", jaccard_score(y_test, y_pred, average=None)[1])\nprint(\"Decision Tree F1-score :\", f1_score(y_test, y_pred, average='weighted'))", "execution_count": 141, "outputs": [{"output_type": "stream", "text": "Decision Tree Jaccard : 0.7571428571428571\nDecision Tree F1-score : 0.6524970963995355\n", "name": "stdout"}]}, {"metadata": {}, "cell_type": "code", "source": "y_pred = SVM_model.predict(X_test)\nprint(\"SVM Jaccard :\", jaccard_score(y_test, y_pred, average=None)[1])\nprint(\"SVM F1-score :\", f1_score(y_test, y_pred, average='weighted'))", "execution_count": 142, "outputs": [{"output_type": "stream", "text": "SVM Jaccard : 0.7571428571428571\nSVM F1-score : 0.6524970963995355\n", "name": "stdout"}]}, {"metadata": {}, "cell_type": "code", "source": "y_pred = LR_model.predict(X_test)\nprint(\"Linear regression Jaccard :\", jaccard_score(y_test, y_pred, average=None)[1])\nprint(\"Linear regression F1-score :\", f1_score(y_test, y_pred, average='weighted'))\n\ny_pred = LR_model.predict_proba(X_test)\nprint(\"Linear regression LogLoss :\", log_loss(y_test, y_pred))", "execution_count": 143, "outputs": [{"output_type": "stream", "text": "Linear regression Jaccard : 0.7571428571428571\nLinear regression F1-score : 0.6524970963995355\nLinear regression LogLoss : 0.5554776938459423\n", "name": "stdout"}]}, {"metadata": {}, "cell_type": "code", "source": "", "execution_count": null, "outputs": []}], "metadata": {"kernelspec": {"name": "python3", "display_name": "Python 3.8", "language": "python"}, "language_info": {"name": "python", "version": "3.8.11", "mimetype": "text/x-python", "codemirror_mode": {"name": "ipython", "version": 3}, "pygments_lexer": "ipython3", "nbconvert_exporter": "python", "file_extension": ".py"}}, "nbformat": 4, "nbformat_minor": 1}